# Site settings
title: LSWT2019
email:
description: ""
baseurl: ""
url: "https://lswt2019.aksw.org"
description: "Der Leipziger Semantic Web Tag (LSWT) bietet seit 2009 WissenschaftlernInnen, Unternehmen und Organisationen die Möglichkeit, sich zu Themen im Bereich semantischer Technologien auszutauschen.
Diese Schwerpunkte werden im Rahmen von Vorträgen durch ExpertenInnen aus Industrie und Wissenschaft demonstriert (<a href="#Programm">Programm</a>).
Falls Sie weitere Fragen haben können Sie sich auch gerne an das <a href="#Team">Organisations-Team</a> wenden."
twitter_username: aksw
github_username:  aksw

# Build settings
permalink: /:year/:month/:day/:title
timezone: Europe/Berlin
markdown: kramdown
kramdown:
  parse_block_html: true

# Build settings
#theme: minima
plugins:
  - jekyll-rdf
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - src
jekyll_rdf:
    path: "_data/graph.ttl"
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"https://lswt2019.aksw.org/\") }"
    class_template_mappings:
        "http://purl.org/dc/terms/BibliographicResource" : "publication.html"
        "http://xmlns.com/foaf/0.1/Document" : "page.html"
