# Site settings
title: LSWT2019
email:
description: ""
baseurl: ""
url: "https://lswt2019.aksw.org"
rootResource: "<https://lswt2019.aksw.org/>"
translations:
  de: https://lswt2019.aksw.org/
  en: https://lswt2019.aksw.org/en/
twitter_username: akswgroup
github_username:  aksw

# Build settings
permalink: /:year/:month/:day/:title
timezone: Europe/Berlin
markdown: kramdown
kramdown:
  parse_block_html: true

# Build settings
#theme: minima
plugins:
  - jekyll-rdf
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - src
jekyll_rdf:
    path: "graph.ttl"
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"https://lswt2019.aksw.org/\") }"
    class_template_mappings:
        "http://purl.org/dc/terms/BibliographicResource" : "publication.html"
        "http://xmlns.com/foaf/0.1/Document" : "page.html"
